apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  strategy:
    #type: Recreate
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hello
  replicas: 3
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          # enter the path to your image, be sure to include the correct region prefix
          image: sjc.ocir.io/axwrtlp0n4xv/customapp:custom
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 80
      imagePullSecrets:
        # enter the name of the secret you created
        - name: secret
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: hello